apiVersion: agentswarm.dev/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: agent-swarm
    app.kubernetes.io/managed-by: kustomize
  name: mock-repo
spec:
  owner: pontusc
  repo: mock-repo
  syncIntervalSeconds: 60
  secretRef:
    name: github-app-creds
